#******************************************************************************
#
# Default memory map for Apollo330P
#
# The setting of STACK end address is a workaround for hang up at bootroom
# when loading keil6 binary
#
#******************************************************************************
MemorySections:
    MCU_MRAM:
        start:  0x00410000
        end:    0x005FFFFF

    MCU_TCM:
        start:  0x20000000
        end:    0x2003EFFF

    SHARED_SRAM:
        start:  0x20080000
        end:    0x2023FFFF

    STACK:
        start:  0x2003F000
        end:    0x2003FFFF

    HEAP:
        start:  0x60000000
        end:    0x607fffff
